@startuml Comptabilité CPE

abstract class Enseignant {

}

class EnseignantPermanent extends Enseignant {

}

class Vacataire extends Enseignant {

}

class Doctorant extends Enseignant {

}

enum TypeEnseignant {

}

class ChargePatronale {

}

@enduml